### ISSUE TITLE
Error: "Animation Armature" on model with no skeleton

### ISSUE THREAD

**Issue by 09williamsad** [AsteriskAmpersand/Mod3-MHW-Importer#3]
Blender version: 2.79b 2018-3-22 14:10
Importer version: latest as of 2019/7/4
MHW game version: 167589

Issue:
When importing a .mod3 file with the "Import Skeleton" setting set to "Animation Armature" but the model does not have a skeleton an error will occur.
This is not a problem for regular usage but batch conversion of models with and without skeletons will run into the error.
Occurs on the accessory acc011_002, files used https://mega.nz/#!2DZU0aIA!4dQN_qmfO0g_ZgAKy80DwpG6IuBdtzycRQgzMegA9qA

Suggestion:
A check on import so that if "Animation Armature" is selected and the model does not have a skeleton then armature import is skipped.

Console Error:
Traceback (most recent call last):
  File "C:\Users\Adam\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Mod3-MHW-Importer-master\operators\mod3import.py", line 102, in execute
    Mod3IL.Mod3ToModel(Mod3File, BApi, options).execute(blenderContext)
  File "C:\Users\Adam\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Mod3-MHW-Importer-master\mod3\Mod3ImporterLayer.py", line 37, in execute
    call(context)
  File "C:\Users\Adam\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Mod3-MHW-Importer-master\mod3\Mod3ImporterLayer.py", line 49, in <lambda>
    excecute.append(lambda c: skeletonOperator(c))
  File "C:\Users\Adam\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Mod3-MHW-Importer-master\mod3\Mod3ImporterLayer.py", line 83, in createArmature
    self.api.createArmature(self.model.prepareArmature(),c)
  File "C:\Users\Adam\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Mod3-MHW-Importer-master\blender\BlenderMod3Importer.py", line 100, in createArmature
    boneGraph = BoneGraph(armature)
  File "C:\Users\Adam\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Mod3-MHW-Importer-master\blender\BlenderMod3Importer.py", line 41, in __init__
    self.roots = self.boneParentage[255]
KeyError: 255

**Comment by AsteriskAmpersand** [comment]
This requires reviewing the animation armature code and it'd be more than a simple check, ti's rewriting the base case so it covers all of them and doesn't rely on a check but the way iterators naturally work on the language. If animation exporting is ever possible I'd extend the code for the animation armature to also be exportable directly (currently this provides no benefit because the animation armature is not a true armature in the sense that anyone with 3d modelling background would expect) which is why I'm tryign to keep that section of the code relatively clean despite being a "curiosity" for now.

I'll consider this if I have time, but it's not a priority on my list, much less on this particular project. The hack patch of checking is not hard to write (it's just a try catch, if you are batching you can outright include it on a script and use the alternative empty structure for those) but I'm not pushing that on this repo anytime soon.
