### ISSUE TITLE
Animation Armature not importing

### ISSUE THREAD

**Issue by zStatykz** [AsteriskAmpersand/Mod3-MHW-Importer#9]
Blender 2.80 with the most recent plugin version.

Tried to import an Animation Armature with the Vaal Hazak Y body (pl032_0020) and got this error:

```
bpy.data.window_managers["WinMan"].(null)` = 'Armature'
bpy.context.space_data.bookmarks_active = 0
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete()
Traceback (most recent call last):
  File "C:\Users\Brandon\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\Mod3-MHW-Importer-master\operators\mod3import.py", line 102, in execute
    Mod3IL.Mod3ToModel(Mod3File, BApi, options).execute(blenderContext)   
  File "C:\Users\Brandon\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\Mod3-MHW-Importer-master\mod3\Mod3ImporterLayer.py", line 37, in execute
    call(context)
  File "C:\Users\Brandon\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\Mod3-MHW-Importer-master\mod3\Mod3ImporterLayer.py", line 49, in <lambda>
    excecute.append(lambda c: skeletonOperator(c))
  File "C:\Users\Brandon\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\Mod3-MHW-Importer-master\mod3\Mod3ImporterLayer.py", line 83, in createArmature
    self.api.createArmature(self.model.prepareArmature(),c)
  File "C:\Users\Brandon\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\Mod3-MHW-Importer-master\blender\BlenderMod3Importer.py", line 93, in createArmature
    bpy.context.scene.update()
AttributeError: 'Scene' object has no attribute 'update'```

**Comment by AsteriskAmpersand** [comment]
Fixed on latest push.
